---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
spec: 
  selector: 
    matchLabels: 
      app: mysql
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers: 
      - name: mysql 
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 123.com
        ports: 
        - containerPort: 3306
        volumeMounts: 
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes: 
      - name: mysql-persistent-storage
        persistentVolumeClaim: 
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql
spec: 
  type: LoadBalancer
  ports: 
  - port: 3306
    targetPort: 3306
  selector: 
    app: mysql