kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    image: busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS && exit 0 || exit 1"   #创建一个SUCCESS文件后退出
    volumeMounts:
      - name: nfsstorage-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfsstorage-pvc
      persistentVolumeClaim:
        claimName: test-claim  #与PVC名称保持一致