apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30040
  selector:
    app: mongo-standalone-nfs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo-standalone-nfs
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo-standalone-nfs
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: "/data/db"
              name: mongo
      volumes:
      - name: mongo
        persistentVolumeClaim:
          claimName: mongo

          
---
## PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo
  labels:
    app: mongo             #设置 pv 的 label 标签
spec:
  capacity:          
    storage: 5Gi           #设置 pv 存储资源大小 
  accessModes:       
  - ReadWriteOnce
  mountOptions:
  - hard
  - nfsvers=4.1    
  nfs:                     #指定使用 NFS 存储驱动
    server: 10.15.1.48   #指定 NFS 服务器 IP 地址
    path: /data/nfs/mongo       #指定 NFS 共享目录的位置，且需提前在该目录中创建 mongo 目录
  persistentVolumeReclaimPolicy: Retain  
---
## PVC
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo
spec:
  resources:
    requests:
      storage: 5Gi         #设置 pvc 存储资源大小
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      app: mongo           #根据 Label 选择对应 PV
